### PR TITLE
Fix: Implement sort when storing multi-select values to cache.

### LINKED ISSUE #16: Implement consistent chain ordering
Chains in tables and charts are displayed in an arbitrary order. This usually starts off as parse order, but deselecting and reselecting a chain inserts the most-recently-selected chain at the end of the list. This causes reorderings of table rows in the "Tables" tab, and changes the Z-axis (overlap) ordering of the chains as displayed in the charts on the "Diagnostics" and "Scatterplots" tabs.

To fix: implement a sorting operation for data before it is returned from cache and/or sort chains (sequences, etc) by key text.

### PR DESCRIPTION
**Pull request by jsoules**
Fixes #16.

Acceptance test:

- View example data with PR code and current prod.
- Chain selection:
  - In Prod "Diagnostics" tab, confirm that deselecting and reselecting chain 1 will cause chain 1 to be displayed on top of the other chains in the graph, i.e. drawn last.
  - In this code, confirm that deselceting and reselecting chain 1 results in the same image (z-ordering) as on initial load.
- Load "Tables" tab in both versions.
  - Confirm that in prod, adding the `accept_stat__` variable to the initially selected `lp__` puts that `accept_stat__` at the bottom. Deselecting and reselecting `lp__` results in `accept_stat__` bubbling up to the top of the order, with `lp__` now last. Confirm this behavior matches the ordering of the variables display on the Diagnostics tab.
  - In this code, confirm that the same test results in a consistent alphabetical ordering for all selected variables.

Question: Do we want to sort so that `lp__`, if present, is always at the top?

### CODE REVIEW

File: src/MCMCMonitorDataManager/MCMCMonitorData.ts [hunk 1]
```diff
@@ -145,13 +145,13 @@ export const mcmcMonitorReducer = (s: MCMCMonitorData, a: MCMCMonitorAction): MC
     else if (a.type === 'setSelectedVariableNames') {
         return {
             ...s,
-            selectedVariableNames: a.variableNames
+            selectedVariableNames: a.variableNames.sort()
```
Comment (magland) [inline src/MCMCMonitorDataManager/MCMCMonitorData.ts]: In the spirit of immutability it's probably better to do:
```
selectedVariableNames: [...a.variableNames].sort()
```
This avoids having a reference to this part of the state elsewhere in the code.

Comment (jsoules) [reply src/MCMCMonitorDataManager/MCMCMonitorData.ts]: I'm happy to make the change, but wouldn't the unsorted assignment (i.e. what's in `main` right now) be equally at risk of capturing the reference?

What I'd expect to happen (in both cases) is the state is replaced with a new state whose `selectedVariableNames` key points to the list on the incoming `MCMCMonitorAction`, the rest of `a` goes out of scope and gets GC'd, and the new state object just owns the pointer now. Is there something I'm overlooking?

Comment (magland) [reply src/MCMCMonitorDataManager/MCMCMonitorData.ts]: Yes, the same problem existed before your modifications. I think it's better to make a copy.
